# Generated by Django 4.2.6 on 2023-10-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstname',
            name='first_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lastname',
            name='last_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patronymic',
            name='patronymic',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='street',
            name='street',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
