# Generated by Django 4.2.6 on 2023-10-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_firstname_first_name_alter_lastname_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='apartment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='building',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='first_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.firstname'),
        ),
        migrations.AlterField(
            model_name='main',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
